parameters:
  locale: de

enhavo_app:
    menu:
        dashboard:
            type: dashboard
        user:
            type: user_user
        group:
            type: user_group
        article:
            type: article
        page:
            type: page
        translation-strings:
            type: translation
        book:
            type: base
            label: Buch
            route: project_book_index
            role: ROLE_ENHAVO_PROJECT_BOOK_INDEX
            icon: book
        author:
            type: base
            label: Autor
            route: project_author_index
            role: ROLE_ENHAVO_PROJECT_AUTHOR_INDEX
            icon: book

enhavo_grid:
    items:
#        picture:
#            type: picture
#        picture_picture:
#            type: picture_picture
#        three_picture:
#            type: three_picture
#        gallery:
#            type: gallery
        text:
            type: text
            template: ProjectBundle:Theme:Grid/text.html.twig
#        text_picture:
#            type: text_picture
        text_text:
            type: text_text
            template: ProjectBundle:Theme:Grid/text_text.html.twig
#        cite_text:
#            type: cite_text
#        download:
#            type: download
#        video:
#            type: video

sylius_resource:
    resources:
        project.book:
            classes:
                model: ProjectBundle\Entity\Book
                controller: Enhavo\Bundle\AppBundle\Controller\ResourceController
                form:
                    default: ProjectBundle\Form\BookType
        project.author:
            classes:
                model: ProjectBundle\Entity\Author
                controller: Enhavo\Bundle\AppBundle\Controller\ResourceController
                form:
                    default: ProjectBundle\Form\AuthorType

enhavo_translation:
    translate: true
    locales:
        de:
        en:
    translation_strings:
      - navigation.home
      - navigation.book
      - navigation.blog
      - navigation.author
      - navigation.contact
      - author.title
      - blog.title
      - blog.teaser
      - blog.back
      - book.back