project_book_index:
    options:
        expose: true
    path: /project/book/index
    methods: [GET]
    defaults:
        _controller: project.controller.book:indexAction
        _sylius:
            viewer:

project_book_create:
    options:
        expose: true
    path: /project/book/create
    methods: [GET,POST]
    defaults:
        _controller: project.controller.book:createAction
        _sylius:
            viewer:

project_book_update:
    options:
        expose: true
    path: /project/book/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: project.controller.book:updateAction
        _sylius:
            viewer:

project_book_table:
    options:
        expose: true
    path: /project/book/table
    methods: [GET]
    defaults:
        _controller: project.controller.book:tableAction
        _sylius:
            viewer:
                translationDomain: EnhavoArticleBundle
                columns:
                    public:
                        label: article.label.public
                        property: public
                        width: 2
                        type: boolean
                    title:
                        label: article.label.title
                        property: title
                        width: 7
                    publicationDate:
                        label: article.label.publicationDate
                        property: publicationDate
                        type: date
                        width: 3

project_book_delete:
    options:
        expose: true
    path: /project/book/delete/{id}
    methods: [DELETE]
    defaults:
        _controller: project.controller.book:deleteAction

project_book_batch:
    options:
        expose: true
    path: /project/book/batch
    methods: [POST]
    defaults:
        _controller: project.controller.book:batchAction
        _sylius:
            paginate: false
            criteria:
                id: $ids
            batches:
                delete:
                    type: delete

project_book_preview:
    options:
        expose: true
    path: /project/book/preview
    methods: [POST]
    defaults:
        _controller: project.controller.book:previewAction
        _sylius:
            viewer:



