<?php

namespace ProjectBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends EntityRepository
{
    public function findWithStartLetter($firstLetter)
    {
        $query = $this->createQueryBuilder('n');
        $query->andWhere('n.name LIKE :firstLetter');
        $query->setParameter('firstLetter', $firstLetter.'%');
        return $query->getQuery()->getResult();
    }
}
