<?php

namespace ProjectBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{
    public function findPicture($id)
    {
        $query = $this->createQueryBuilder('n');
        $query->andWhere('n.name LIKE :firstPicture');
        $query->setParameter('firstPicture', $id.'%');
        return $query->getQuery()->getResult();
    }
}
