ProjectBundle\Entity\Author:
    type: entity
    table: project_author
    repositoryClass: ProjectBundle\Repository\AuthorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
