ProjectBundle\Entity\Link:
    type: entity
    table: project_link
    repositoryClass: ProjectBundle\Repository\LinksRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255

    manyToOne:
        book:
            cascade: ['persist']
            targetEntity: ProjectBundle\Entity\Book

    lifecycleCallbacks: {  }
