project_default_index:
    path:     /
    defaults: { _controller: ProjectBundle:Default:index }

project_list_index:
    path:     /list
    defaults: { _controller: ProjectBundle:List:index }

project_book:
    prefix:   /admin
    resource: "@ProjectBundle/Resources/config/routing/book.yml"

project_author:
    prefix:   /admin
    resource: "@ProjectBundle/Resources/config/routing/author.yml"