services:
    project.form.book:
        class:  ProjectBundle\Form\BookType
        tags:
            - { name: form.type, alias: 'project_book' }
    project.form.author:
        class:  ProjectBundle\Form\AuthorType
        tags:
            - { name: form.type, alias: 'project_author' }